### ISSUE TITLE
Bug: snapshot issue with huge table

### ISSUE THREAD

**Issue by maksenius** [conduitio-labs/conduit-connector-snowflake#22]
### Bug description

Snapshot iterator sometimes get error about when works with huge table

### Steps to reproduce

Use this config for test
```
pipelines:
  pipeline3:
    status: stopped
    name: Snowflake-TinyBird 
    description: desc
    connectors:
      con1:
        type: source
        plugin: snowflake
        name: snowflake source
        settings:
          connection: ***************
          table: test
          primaryKey: id
      con2:
        type: destination
        plugin: tinybird
        name: tinybird-destination
        settings:
          token: ***********************
          datasource: test
```

Try to work with big tables

### Version

v0.4.0-nightly.20221028-dirty
